- REQUIRED CONFIG CHANGE: Block/Switch/Item_Use Additions for MC 1.16.*     - protection.switch_ids       - Add ",CRIMSON_PRESSURE_PLATE,WARPED_PRESSURE_PLATE,POLISHED_BLACKSTONE_PRESSURE_PLATE,CRIMSON_BUTTON,WARPED_BUTTON,POLISHED_BLACKSTONE_BUTTON,CRIMSON_DOOR,WARPED_DOOR,CRIMSON_FENCE_GATE,WARPED_FENCE_GATE,CRIMSON_TRAPDOOR,WARPED_TRAPDOOR,LODESTONE,RESPAWN_ANCHOR,TARGET"     - protection.item_use_ids       - Add ",NETHERITE_AXE"     - new_world_settings.plot_management.revert_on_unclaim.block_ignore       - Add ",NETHER_GOLD_ORE,ANCIENT_DEBRIS,SOUL_TORCH,SOUL_WALL_TORCH,CRIMSON_SIGN,CRIMSON_WALL_SIGN,WARPED_SIGN,WARPED_WALL_SIGN,LODESTONE,RESPAWN_ANCHOR"       - This will also have to be added to any towny\data\worlds\WORLDNAME.txt file in the plotManagementIgnoreIds list.     - new_world_settings.plot_management.mayor_plotblock_delete.mayor_plot_delete       - Add ",CRIMSON_WALL_SIGN,CRIMSON_SIGN,WARPED_WALL_SIGN,WARPED_SIGN"       - This will also have to be added to any towny\data\worlds\WORLDNAME.txt file in the plotManagementMayorDelete list.     - new_world_settings.plot_management.block_delete.unclaim_delete       - Add ",CRIMSON_SIGN,WARPED_SIGN,CRIMSON_WALL_SIGN,WARPED_WALL_SIGN,CRIMSON_DOOR,WARPED_DOOR,SOUL_TORCH,SOUL_WALL_TORCH,CRIMSON_PRESSURE_PLATE,WARPED_PRESSURE_PLATE,POLISHED_BLACKSTONE_PRESSURE_PLATE"       - This will also have to be added to any towny\data\worlds\WORLDNAME.txt file in the plotManagementDeleteIds list.   - Fix NoSuchMethodError on startup from the new log4j methods.