Fix Errors in JavaDocs (squashed: see commit description)
Just addresses one of the many Javadoc issues it throws.

Javadoc: Errors with impropper @links


Javadoc: Fix Errors

Missing ')' (TownyAPI)
Missing parameter for player (TownyFormatter)
Unrecognized String (caused by < & > (TownyFormatter)
Wrong path to bukkit Player class. (TownyPlaceholderExpansion)

Javadoc Error: 'Unexpected Text' in ResidentCommand

> ResidentCommand.java:521: error: unexpected text
	 * @throws TownyException- Exception.

Resolved adding space after TownyException

JavaDoc Remove @exception and @throws tags

These exceptions are never thrown by the methods they are in. This causes the Javadocs to error out.

Javadoc: Remove invalid use of '@return'

"You should never have come here!"