Generate JavaDocs with Maven, Javadoc cleaning (#3501)
* Add Maven's Javadoc Plugin

* For Automatic Javadoc generation at package phase.
<failOnWarning/Error> prevents the compilation from failing if the javadocs fail.

* Fix Errors in JavaDocs (squashed: see commit description)

* Just addresses one of the many Javadoc issues it throws.

* Javadoc: Errors with impropper @links


* Javadoc: Fix Errors

Missing ')' (TownyAPI)
Missing parameter for player (TownyFormatter)
Unrecognized String (caused by < & > (TownyFormatter)
Wrong path to bukkit Player class. (TownyPlaceholderExpansion)

Javadoc Error: 'Unexpected Text' in ResidentCommand

> ResidentCommand.java:521: error: unexpected text
	 * @throws TownyException- Exception.

Resolved adding space after TownyException

JavaDoc Remove @exception and @throws tags

These exceptions are never thrown by the methods they are in. This causes the Javadocs to error out.

Javadoc: Remove invalid use of '@return'

"You should never have come here!"

* Fill in some empty parameters, returns and throws; add missing.

Just knocks out a bunch of the warnings that javadocs throws upon packaging.

* Erratum: Metadata > Status Screen

Fixes comments to comply with review

* More missing and descriptions, convert some comments to Javadoc

Picking up where I left off with this stuff

* Attempt to fix Line Ending (prevent large diff)

We *really* need to do a PR just to reset all the line endings to CRLF...

* Automation: Javadocs @ Deploy Phase & GitHub Actions

Javadocs now only build at the Maven 'deploy' phase, when the jarfile is built and pushed to the GitHub Package Registry by a CI.   

Normal users can still build JavaDocs manually using `mvn javadocs:jar` from a terminal, or by selecting the plugin in IntelliJ's sidebar.  

This commit also introduces a GitHub Actions workflow file that automatically builds upon a Release or Prerelease - which will push to the Package Registry for us. (As I don't have contributor-level access, this may or may not work out of the box... Trial and error.)

* Make sure javadocs build jarfile

* Move Javadocs Build to the "install" phase

useful for developers who clone the project themselves to use during development.

* - REQUIRED TOWNYPERMS.YML CHANGE: add towny.command.nation.leave to
the mayor group.
    - Closes ticket #3511

* - Language files bumped to 0.64.
  - Fix lack of feedback when adding a nation enemy that doesn't exist.
    - Closes ticket #3512

* Add Maven's Javadoc Plugin

For Automatic Javadoc generation at package phase.
<failOnWarning/Error> prevents the compilation from failing if the javadocs fail.

* Fix Errors in JavaDocs (squashed: see commit description)

Just addresses one of the many Javadoc issues it throws.

Javadoc: Errors with impropper @links


Javadoc: Fix Errors

Missing ')' (TownyAPI)
Missing parameter for player (TownyFormatter)
Unrecognized String (caused by < & > (TownyFormatter)
Wrong path to bukkit Player class. (TownyPlaceholderExpansion)

Javadoc Error: 'Unexpected Text' in ResidentCommand

> ResidentCommand.java:521: error: unexpected text
	 * @throws TownyException- Exception.

Resolved adding space after TownyException

JavaDoc Remove @exception and @throws tags

These exceptions are never thrown by the methods they are in. This causes the Javadocs to error out.

Javadoc: Remove invalid use of '@return'

"You should never have come here!"

* Fill in some empty parameters, returns and throws; add missing.

Just knocks out a bunch of the warnings that javadocs throws upon packaging.

* Erratum: Metadata > Status Screen

Fixes comments to comply with review

* More missing and descriptions, convert some comments to Javadoc

Picking up where I left off with this stuff

* Attempt to fix Line Ending (prevent large diff)

We *really* need to do a PR just to reset all the line endings to CRLF...

* Automation: Javadocs @ Deploy Phase & GitHub Actions

Javadocs now only build at the Maven 'deploy' phase, when the jarfile is built and pushed to the GitHub Package Registry by a CI.   

Normal users can still build JavaDocs manually using `mvn javadocs:jar` from a terminal, or by selecting the plugin in IntelliJ's sidebar.  

This commit also introduces a GitHub Actions workflow file that automatically builds upon a Release or Prerelease - which will push to the Package Registry for us. (As I don't have contributor-level access, this may or may not work out of the box... Trial and error.)

* Make sure javadocs build jarfile

* Move Javadocs Build to the "install" phase

useful for developers who clone the project themselves to use during development.